shared:
  region: "eu-west-2"

development:
  iterations_bucket: exercism-staging-iterations
  profile: exercism_website

test:
  iterations_bucket: exercism-staging-iterations
  profile: exercism_website
