development:
  test_runner_orchestrator_url: "http://127.0.0.1:3021"
  analyzer_orchestrator_url: "http://127.0.0.1:3021"
  representer_orchestrator_url: "http://127.0.0.1:3021"

development_docker:
  test_runner_orchestrator_url: "http://tooling-orchestrator:3021"
  analyzer_orchestrator_url: "http://tooling-orchestrator:3021"
  representer_orchestrator_url: "http://tooling-orchestrator:3021"

test:
  test_runner_orchestrator_url: "http://test-runner.example.com"
  analyzer_orchestrator_url: "http://analyzer.example.com"
  representer_orchestrator_url: "http://representer.example.com"

production:
  test_runner_orchestrator_url: "MISSING_VALUE"
  analyzer_orchestrator_url: "MISSING_VALUE"
  representer_orchestrator_url: "MISSING_VALUE"
