name: Push to DockerHub

on:
  push:
    branches: [main]

jobs:
  dockerhub:
    # TODO: Change this to website when merging
    if: github.repository == 'exercism/v3-website'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          # Change these to rest the cache
          key: docker-layer-caching-dockerhub-{hash}
          restore-keys: docker-layer-caching-dockerhub-
          concurrency: 30

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: exercism/website
          tag_with_sha: true
          tags: latest
          dockerfile: dev.Dockerfile
